### ISSUE TITLE
ModuleNotFoundError:  'utils.middleware.maintenance' While running testcases

### ISSUE THREAD

**Issue by pawan-betrics** [fabiocaccamo/django-maintenance-mode#142]
**Python version**
3.9.16

**Django version**
4.0.5

**Package version**
django-maintenance-mode==0.18.0

**Current behavior (bug description)**
```
System check identified no issues (0 silenced).
E...
======================================================================
ERROR: utils.middleware (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: utils.middleware
Traceback (most recent call last):
  File "/home/pc/.pyenv/versions/3.9.16/lib/python3.9/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/home/pc/.pyenv/versions/3.9.16/lib/python3.9/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/pc/Documents/betrics-backend/betrics/utils/middleware/__init__.py", line 1, in <module>
    from .maintenance import MaintenanceModeMiddleware
ModuleNotFoundError: No module named 'utils.middleware.maintenance'
```

**Expected behavior**
It should not return this module import error

Settings.py
```

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "maintenance_mode.middleware.MaintenanceModeMiddleware",
]

# if True the maintenance-mode will be activated
MAINTENANCE_MODE = (
    True
    if os.environ.get("MAINTENANCE_MODE")
    in (
        "1",
        1,
        "true",
        "True",
    )
    else False
)

MAINTENANCE_MODE_IGNORE_ADMIN_SITE = True  # if True admin site will not be affected by the maintenance-mode page
MAINTENANCE_MODE_RETRY_AFTER = 3600  # 1 hour
MAINTENANCE_MODE_IGNORE_TESTS = True
```

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/fabiocaccamo/django-maintenance-mode/issues/142">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/fabiocaccamo/django-maintenance-mode/issues/142/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/fabiocaccamo/django-maintenance-mode/issues/142/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment]
@pawan-betrics the module not found `utils.middleware.maintenance` is not a module of this library.
